### ISSUE TITLE
에셋 목록 뽑기

### ISSUE THREAD

**Issue by jjpark78** [jjpark78/angrybird-bthl#3]
### 게임에 필요한 이미지들의 목록을 리스트업 해주세요

* 영의 열매 다양한 특성들 -> 과일 이미지의 배경에 문자 합성
* 게임의 배경 이미지 
* 앵그리 버드 캐릭터 이미지 ->  준이 & 지나 캐릭터로 변경
* 새총 이미지 -> ???

**Comment by jeong** [comment]
이미 디자인 진행 중이라 이 이슈는 종료합니다.
