### ISSUE TITLE
게임 시작 전에 애니메이션 화면 보여주기

### ISSUE THREAD

**Issue by jjpark78** [jjpark78/angrybird-bthl#4]
1. CSS 컨테이너로 화면 대부분을 덮음. 애니메이션 자동 재생 시작
2. 애니메이션 재생 종료후 애니메이션 컨테이너 히든 처리,  "시작 할까요" 메세지가 표시된 새로운 컨테이너 표시
3. 엔터나 스페이스키 입력에 반응해서 새로운 메세지 컨테이너 히든 처리
4. 메인 화면 등장

**Comment by jeong** [comment]
@jjpark78 애니메이션은 앱스에서 선정하는 건가요? 여기 참고 사이트(https://github.com/jjpark78/angrybird-bthl/discussions/7) 중에서 고르고요?

**Comment by jjpark78** [comment]
어. 일단 제가 화면 전환을 좀 하기 쉽게 async 함수 단위로 수행되게 변경했구요, 
애니메이션 말고 이미지 + 키보드 이벤트로 화면 전환 받기로 했어요. 
최신 코드 커밋한거 봐주세용.

**Comment by jeong** [comment]
김은수 형제가 작성한 코드도 있습니다. 일단 기능은 추가되었으니 이슈 닫을게요.
