### ISSUE TITLE
김은수 형제의 코드 베이스 머지하기

### ISSUE THREAD

**Issue by jjpark78** [jjpark78/angrybird-bthl#8]
김형제의 코드가 상당부분 진행이 많이 되었기 때문에 해당 코드에서 출발하도록 합시다.

**Comment by ciriris** [comment]
"base commit" 으로 push 완료했습니다.

**Comment by jjpark78** [comment]
다음에는 다이렉틑 푸시 말고 브랜치 pull request로 해주세용.
